name:     ac-haskell
version:  0.1.0
synopsis: A streaming implementation of arithmetic coding
category: Compression
author:   Konrad Kleczkowski <konrad.kleczkowski@gmail.com>
license:  MIT

dependencies:
- base == 4.* && < 5.0
- bytestring
- pipes
- pipes-bytestring
- pipes-group
- fixed
- mtl
- lens
- transformers
- primitive
- vector

ghc-options:
- -Wall
- -fno-warn-name-shadowing

library:
  source-dirs:    src
  ghc-options:
  - -O2

executables:
  ac-haskell:
    source-dirs:  app
    main:         Main.hs
    dependencies:
    - ac-haskell
    - optparse-applicative

tests:
  ac-haskell-spec:
    source-dirs:  test
    main:         Spec.hs
    dependencies:
    - ac-haskell
    - hspec
    - QuickCheck
    - random
    - bytestring-arbitrary

benchmarks:
  ac-haskell-bench:
    source-dirs:  bench
    main:         Bench.hs
    dependencies:
    - ac-haskell
    - criterion
    - mwc-random
    - random-bytestring
